typography_spectrum: 0.6069257583003491
color:
  brandStrength: 0.3238762435503304
  lightness: 0.5242268592119217
  saturation: 0.6981371152214706
  rhythmicContrast: 0.5250435767229646
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.0822053023148328
author:
  name: John Oliver
  email: dee.gandhi@gmail.com
  url: www.AlokaCreative.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cae0df3f-cfc6-4463-adb5-fc7864419c09.jpg
name: Aloka Creative Inc.
navigation:
  - name: Images
    url: www.Alokacreative.com
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e708117e-5465-4128-9db5-f3eaf74ba350.jpg
title: 'Aloka Creative '
description: Attention is Currency... Get Some.
